sudo: false
language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install coverage
  - pip install coveralls
# command to run tests
script: nosetests --with-coverage --cover-package=ddby
after_success:
  coveralls
